import React from 'react';
import Head from 'next/Head';

export default function Layout({title, children}) {
  return  (<div className='bg-gray-300'>
            <Head>
              <title>{title}</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="pt-8">
              {children}
            </main>
          </div>
          );
}
